---
title: "CitableBase"
---


This package defines traits and abstract types for the essential concepts of the CITE architecture.


| | Learning the package | Using the package |
| --- | --- | --- |
| **Hands-on** |  Try a [tutorial](./tutorials/) to start using  the package  | Find [recipes](./guides/) for specific tasks |
| **Cognition** | Learn [concepts](./concepts/)   | See [reference information](./reference/) (including API documentation for all exported functions) |





## Contents of this user's guide

It is perfectly possible to use packages implementing the abstractions of `CitableBase` without understanding how `CitableBase` is designed.  This user's guide is for anyone who needs to build their own custom implementations or simply wishes to understand how these abstractions can be implemented.

The guide works through a hypothetical example to design a reading list of books citable by URN values.  The guide first illustrates how to implement a custom URN type for ISBN-10 numbers. It then creates a custom citable object for books cited by ISBN-10 numbers, and finally defines a custom citable collection representing a reading list.  

Following the user's guide, the documentation includes the formal API documentation for the exported functions and types of the `CitableBase` package.